### ISSUE TITLE
file follower: don't stop on a corrupt state file

### ISSUE THREAD

**Issue by david-fritz-gravwell** [gravwell/gravwell#1032]
Currently we refuse to start if the state file can't be read in file follower. Instead, we should copy the corrupt file to a .backup or something, and startup with a new, empty state file.

**Comment by john-floren-gravwell** [comment]
https://github.com/gravwell/gravwell/pull/1080 once this goes in, we can re-test and close

**Comment by john-floren-gravwell** [comment]
lgtm
