### ISSUE TITLE
HTTP Ingester: embedded HTTP logger is throwing non-RFC5424 messages

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#1068]
## What are the steps to reproduce this issue?

1. Fire up HTTP ingester connected to system
2. Enable HTTPS/TLS keys
3. Hit the server with some garbage (causing a TLS error)

## What happens?

Message is emitted in its raw form from the HTTP server/TLS handler that is not well formed

## What were you expecting to happen?

wrap the HTTP server errors in our logger so that messages are always well formed

## Any logs, error output, etc?

```
2024/04/17 19:28:32 server.go:3212: http: TLS handshake error from 7.8.9.0:54342: read tcp 1.2.3.4:443->7.8.9.0:54342: i/o timeout
```

## Any other comments?

We also may not really even WANT the embedded HTTP server messages if we aren't in `INFO` level, its almost always garbage.

## What versions of software are you using?

5.4.7

**Comment by david-fritz-gravwell** [comment]
LGTM
