### ISSUE TITLE
HTTP Ingester is eating SIGABRT and other backtrace inducing errors

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#1081]
## What is the enhancement to be made?

Figure out why http ingester does not backtrace from SIGABRT

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

SIGABRT is useful for grabbing back traces when the ingester is being weird

## Any other comments?

All other ingesters behave fine.

**Comment by ashnwade** [comment]
We have gotten several more SIGABRT crashes with empty stacktraces. Looks like these are showing up for multiple components. Several of them that showed up today for v5.4.10-beta1 came from Lawrence, so please work with him to figure out what is going on.

**Comment by john-floren-gravwell** [comment]
Every component which sent empty stacktraces is a component which has a capability set. In Linux, processes started with (a subset of?) capabilities cannot dump core:

```
[core cannot be dumped if] The process is executing a set-user-ID (set-group-ID) program
          that is owned by a user (group) other than the real user
          (group) ID of the process, or the process is executing a
          program that has file capabilities (see [capabilities(7)](https://www.man7.org/linux/man-pages/man7/capabilities.7.html)).
          (However, see the description of the [prctl(2)](https://www.man7.org/linux/man-pages/man2/prctl.2.html) PR_SET_DUMPABLE
          operation, and the description of the
          /proc/sys/fs/suid_dumpable file in [proc(5)](https://www.man7.org/linux/man-pages/man5/proc.5.html).)
```

I have verified that after setting cap_net_bind_service=+eip on a trivial test program (below), stack traces no longer appear on SIGABRT:

```
package main

import "gravwell/pkg/utils"

func main() {
	quitSig := utils.GetQuitChannel()

	<-quitSig
}
```

**Comment by ashnwade** [comment]
This needs further investigation and probably needs coordination with the go team. Punting out to be reviewed again later.

**Comment by ashnwade** [comment]
This is an intentional go runtime behavior. Won't fix.
