### ISSUE TITLE
Kafka Consumer: config specifies single leader, it should support multiple

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#1145]
## What is the feature to be added?

The kafka consumer configuration should support multiple leaders

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

Kafka does dynamic leader configuration so consumers should be able to hit up any of the bootstrap leaders.

We currently only accept a single leader in the config, but then we turn around an cast that single leader into a slice.

consumer.go:143
```
if clnt, err = sarama.NewConsumerGroup([]string{kc.leader}, kc.group, cfg); err != nil {
       return
}
```

We should support multiple leaders all the way down

## How does this feature address the above problem?

Allows for specifying multiple bootstrap nodes which improves resiliency.

## Any other comments?

Simple code fix, should be fast.

**Comment by david-fritz-gravwell** [comment]
LGTM
