### ISSUE TITLE
make tag cache writing atomic to avoid bombing out on cache on a failed write

### ISSUE THREAD

**Issue by djfritz** [gravwell/gravwell#115]

**Comment by traetox** [comment]
I don't think the ingesters should follow these rules:

1. Do not maintain a handle on the tagcache file.
2. When updating, write to a new file, call sync, and close it
3. Use https://github.com/google/renameio to then swap the temp file in for the original

**Comment by traetox** [comment]
during startup, i think we can also add a code path that looks at the file and if we get an io.EOF on the decode, check if the file is empty, if it is, ignore the error.

**Comment by djfritz** [comment]
renamio provides an atomic writefile(), which covers the original comments, so that's the path we'll take. re: EOF, I'll roll that in.

**Comment by traetox** [comment]
can this be closed @djfritz
