### ISSUE TITLE
file follow: regex delimited files can drop the last entry in a file

### ISSUE THREAD

**Issue by david-fritz-gravwell** [gravwell/gravwell#1291]
## What are the steps to reproduce this issue?

1. Create a regex delimited stanza, something like `foo...`
2. Ingest some data that hits on this.
3. Do something like delete/rotate the file.

## What happens?

The last hit in the file doesn't appear to be ingested.

## What were you expecting to happen?

Ingest.

## What versions of software are you using?

5.4.11 (at least).

**Comment by john-floren-gravwell** [comment]
lgtm, fritz and kris have tested mac and windows respectively
