### ISSUE TITLE
ingesters need to send an announcement log 

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#257]
when an ingester starts it needs to throw an announcement log that contains the following in the structured data portion:

1. Version
2. Name
3. UUID
4. parent process
5. exe path or current EXE

Some optional items that still might be useful
1. loaded preprocessors
2. hash of binary

**Comment by traetox** [comment]
this is basically done, right?

**Comment by djfritz** [comment]
Yes, this is done via config blocks in the ingestMuxer + handshake
