### ISSUE TITLE
Add method to ingest muxer to be able to set and remove "children"

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#305]
Goal here is for ingesters like SimpleRelay and FileFollow to be able to report things connected to them and/or files being followed upstream in the metadata/child structure.

Something like "AddChild(v string)" and "DeleteChild(v string)" if possible

**Comment by floren** [comment]
We already have the RegisterChild and UnregisterChild functions. Those register an "IngesterState" struct, but I think we could very easily extend that struct a bit to encompass more generic stuff. It already has "Metadata" and "Configuration" fields which are json.RawMessage type, plus Name and Size and Tags and other things which could be useful.

RegisterChild is currently only used by the federators, so to my mind it makes sense to just extend it a little bit so we can give information about non-ingester "children". That way, federators will properly pass information about the children of children etc.

**Comment by traetox** [comment]
ok, so done and done
