### ISSUE TITLE
new plugin: syslog router

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#316]
everyone sucks at syslog, add a new plugin that can do routing based on hostname and appname/tag.

use this: https://github.com/jeromer/syslogparser

**Comment by floren** [comment]
Things we might route on:

* application name
* hostname
* msgid
* priority/facility/severity
* message (maaaaaybe)
* structured data ID
* contents of a structured data item

the last two aren't really possible with that library

**Comment by david-fritz-gravwell** [comment]
It would be pretty trivial and quick to write a flexible syslog parser in pbpg if there isn't a library that can do the structured extraction, etc., for us.
