### ISSUE TITLE
AWS Kinesis Delivery Stream ingest issues

### ISSUE THREAD

**Issue by dctootall** [gravwell/gravwell#339]
AWS has introduced a new tool connected to the Kinesis Product,  the "Kinesis Firehose Delivery Stream".     This tool is designed to allow AWS to Deliver Data from a source,  such as the Kinesis Data Stream or a Direct PUT into the Delivery pathway,  to a Destination such as AWS Open Search, S3 Bucket, or Redshift.  It also supports 3rd party Delivery to locations such as Datadog, Splunk, Dynatrace, LogicMonitor, MongoDB Cloud, NewRelic, Sumo Logic,  Or a custom HTTP Endpoint.

Our Existing Kinesis Ingester is designed to work with the Kinesis Data Streams,    however for existing workflows using a Delivery Stream or some AWS products which use a Direct PUT into the Delivery stream to export data,  This ingester will not work.

Unfortunately our HTTP Ingester also does not work due to some custom request/response requirements that AWS has.  

If we attempt to use AWS' Splunk ingester with the HEC Listener,  it fails due to AWS Requiring Splunk's HEC Ack functionality being enabled which we do not support within the ingester currently.     This functionality may actually be a preferred method to implement due to wider potential support/desire for a direct HEC plugin replacement.

**Comment by dctootall** [comment]
Dump of Demo stock ticker type data attempted to import into Gravwell via the http ingester with authentication disabled:

[5976165362.zip](https://github.com/gravwell/gravwell/files/7936519/5976165362.zip)

  AWS Reported the delivery as a failure:

`The response received from the endpoint is invalid. See Troubleshooting HTTP Endpoints in the Firehose documentation for more information. Reason:. Response for request ccbeeb8e-b473-4064-86d5-b50fac45b29d must contain a 'content-type: application/json' header. Raw response received: 200:`

Firehose Request/Response Specs:   [https://docs.aws.amazon.com/firehose/latest/dev/httpdeliveryrequestresponse.html](https://docs.aws.amazon.com/firehose/latest/dev/httpdeliveryrequestresponse.html)

HTTP Ingester Verbose output: 

  `HEADERS map[Content-Length:[314] Content-Type:[application/json] User-Agent:[Amazon Kinesis Data Firehose Agent/1.0] X-Amz-Firehose-Access-Key:[Gravwell on6O6ekLYixvlgDXdV7dprvapHIzxcQK] X-Amz-Firehose-Protocol-Version:[1.0] X-Amz-Firehose-Request-Id:[5d342fea-527d-444a-8e1b-0ac15efdc14f] X-Amz-Firehose-Source-Arn:[arn:aws:firehose:us-west-2:400526119735:deliverystream/Gravwell_http_Ingest]]`

**Comment by dctootall** [comment]
Splunk Documentation on the HEC Acknowledgement functionality:

https://docs.splunk.com/Documentation/Splunk/8.2.4/Data/AboutHECIDXAck

**Comment by traetox** [comment]
`tag=Test1 json -x records requestId timestamp records | json -e records data | base64 -t decoded -d data | table requestId timestamp decoded` cracks the data cleanly and the responses expected are pretty straight forward.

We can fix this
