### ISSUE TITLE
Neucache isn't creating cache directory on Windows

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#35]
## What I did

Enabled cache on windows using neucache system

## What happened

It puked

## Logs and messages

`Failed to start: Failed build our ingest system: CreateFile C:\ProgramData\gravwell\eventlog\events.cache\e: The system cannot find the path specified.`

**Comment by djfritz** [comment]
https://github.com/gravwell/gravwell/blob/dev/chancacher/chancacher.go#L101

The very first thing we do is a mkdirall call... Is it that . isn't allowed as a directory name on windows?

**Comment by djfritz** [comment]
Fixed by #34
