### ISSUE TITLE
File follower must handle ErrEventOverflow

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#362]
Basically if the file follower falls behind it we can get errors coming from readEvents.  We need to catch the ErrEventOverflow and ignore it while re-initializing and/or cleaning up a follower.  In the case of Closing the follower, ignore it.

In the case of actively reading we need clean/reinit/recover from it and continue on.  it is not a critical error

See the following:

https://github.com/fsnotify/fsnotify/blob/master/inotify.go#L251
https://man7.org/tlpi/code/online/dist/inotify/inotify_dtree.c.html#reinitialize

**Comment by floren** [comment]
Do you have a good path for reproducing this in testing?

**Comment by traetox** [comment]
i do not at all, only got this error log:
```
<11>1 2022-02-28T09:05:32.762294+09:00 hostname filefollow - fileFollow/main_linux.go:283 [gw@1 error="fsnotify queue >overflow"] failed to close file follower
```
