### ISSUE TITLE
packetfleet: invalid queries make in the active transactions list

### ISSUE THREAD

**Issue by djfritz** [gravwell/gravwell#37]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/4811604/86023265-b0eb8e00-b9e8-11ea-9cfc-30c05f5eadea.png">

Invalid queries flag as being invalid correctly, but still make it into the running transactions list after a refresh.

**Comment by michaelwisely** [comment]
The packetfleet server seems sending those invalid status items back to the GUI.

**Comment by traetox** [comment]
can this be closed?
