### ISSUE TITLE
filefollow creates inotify handle before invoking Catchup()

### ISSUE THREAD

**Issue by djfritz** [gravwell/gravwell#372]
... and routine() isn't started until after Catchup is completed. If catchup takes a long time and there are active inotify events in the watched directories, this could overflow the inotify kernel buffer.

https://github.com/gravwell/gravwell/blob/dev/ingesters/fileFollow/main_linux.go#L186
https://github.com/gravwell/gravwell/blob/dev/ingesters/fileFollow/main_linux.go#L268
https://github.com/gravwell/gravwell/blob/dev/ingesters/fileFollow/main_linux.go#L275

**Comment by traetox** [comment]
this still a problem?

**Comment by djfritz** [comment]
no -- the current implemented approach was confirmed to be correct.
