### ISSUE TITLE
windows ingester installer

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#39]
Bug report indicating that the `Ingester-UUID` and `Ingest-Secret` are being put on the same line when installing.

Exact bug report:
```
It looks like there’s a slight bug with the windows installer.  When it creates the config file, it puts the Ingestser-UUID and Ingest-Secret on the same line.  I’m not sure if this prevents it from working or not, but wanted to let you know it was happening as I don’t think that’s desirable.
```

**Comment by djfritz** [comment]
I'm unable to reproduce from dev - Building the MSI and pointing the installer to my local gravwell instance with IngestSecrets works fine on install, and the ingester immediately connects.
