### ISSUE TITLE
custom timeformat processing pattern

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#390]
Right now we can provide a regex and a direct timestamp format that needs to work with `time.Format`  But this means we can't handle things like "time=<unixms>".

I propose another field and processing method on the TimeFormat structure that lets you specify a timegrinder format name (like unixmilli).

This way the format can extract an embedded timestamp using a regex, then employ the existing timegrinder extractors against it.

**Comment by kris-watts-gravwell** [comment]
when we do implement this, deprecate the regex-time-prepocessor.  this should happen on a minor release.  Bumping.

**Comment by kris-watts-gravwell** [comment]
I would like to punt this to a later release, its a feature and not important.

**Comment by kris-watts-gravwell** [comment]
this keeps showing up, we are constantly having to deploy preprocessors to catch timestamps that are deeply embedded unix timestamps or JSON with unixmilli on some weird deeply embedded field.

Bumping forward on priority

**Comment by ashnwade** [comment]
Done: https://github.com/gravwell/gravwell/pull/915
