### ISSUE TITLE
Preprocessor Drop-Misses/Passthrough-Misses Standardization

### ISSUE THREAD

**Issue by dctootall** [gravwell/gravwell#469]
## Who was the customer who requested this feature?

Issue Identified while assisting "shadysandman" in Discord

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

2 issues were identified that should be addressed:

1.   Drop-Misses and Passthrough-Misses are used in different preprocessor types to accomplish similar goals.  The lack of standardization on one however caused confusion for a customer as he was using the wrong Option for his specific type.

 _We should standardize on either the Drop or Passthrough option within preprocessors to help simplify config design and remove potential for future customer confusion_

2.   In the Regexextractor preprocessor type,  the lack of the Passthrough-Misses option resulted in a default behavior of dropping data.      Having a default behavior that drops data within the ingester is counter to the Gravwell core ideas of ingesting everything.

   _We should not have a default behavior that drops data unless you have explicitly told it not to do so within the ingesters_

## How does this feature address the above problem?

  Standardizing on one option and removing the default implicit drop data behavior will simplify the preprocessor syntax and remove potential for customer confusion and the resulting misconfigurations that could result in undesired data loss.

## Any other comments?

__Original Discord Thread__

```
shadysandman — Today at 1:14 AM
Hi all,   not sure if this is the right channel.  I have been figuring out configuration of the Simple Relay for syslog.  Had it going fine quickly,  then I have some feeds that come via syslog containing JSON.   So I wanted to tag them as something other than syslog and extract the JSON.   I thought this config should do that.


[Listener "syslogtcp"]
        Bind-String="tcp://0.0.0.0:601" #standard RFC5424 reliable syslog
        Reader-Type=rfc5424
        Tag-Name=syslog
        Assume-Local-Timezone=true #if a time format does not have a timezone, assume local time
        Preprocessor=rfc5424router
        Preprocessor=rfc5424json_extract

[Listener "syslogudp"]
        Bind-String="udp://0.0.0.0:514" #standard UDP based RFC5424 syslog
        Reader-Type=rfc5424
        Tag-Name=syslog
        Assume-Local-Timezone=true #if a time format does not have a timezone, assume local time

[preprocessor "rfc5424router"]
    Type=regexrouter
    Drop-Misses=false
    Regex="^<\\d+>\\d? \\S+ \\S+ (?P<app>\\S+)"
    Route-Extraction=app
    Route=swarm-cron:swarm-cron
    Route=exim:eximsmtp

[Preprocessor "rfc5424json_extract"]
    Type=regexextract
    Drop-Misses=false
    Tag-Name=swarm-cron
    Regex="\\S+ (?P<host>\\S+) \\d+ \\S+ \\S+ (?P<data>\\{.+\\})$"
    Template="{\"host\": \"${host}\", \"data\": ${data}}"

However any syslog events which don't contain JSON are dropped when this configuration is in place.  Thinking I am doing something wrong but cannot figure it this far. 

```
...

**Comment by kris-watts-gravwell** [comment]
we can never deprecate the old config options, but i think the passthrough-misses can become an undocumented option that inverts the "drop-misses"

**Comment by john-floren-gravwell** [comment]
if passing misses becomes the default, then we can just ignore the parameter entirely. Maybe detect and complain if somebody manually sets Drop-Misses and Passthrough-Misses

**Comment by kris-watts-gravwell** [comment]
Going with `Drop-Misses` with it setting itself to false as default, this way we default to always sending stuff

**Comment by kris-watts-gravwell** [comment]
preprocessors that need to be updated:

- CiscoISE
- RegexExtract
- JsonExtract
- JsonSplit

wiki needs to be updated too.
