### ISSUE TITLE
Processor ProcessBatch appears to munge intermediate tags

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#545]
### What are the steps to reproduce this issue?

1. use this function https://pkg.go.dev/github.com/gravwell/gravwell/v3/ingest/processors#ProcessorSet.ProcessBatch

### What happens?

this error: `<11>1 2022-11-15T14:14:43.2796-07:00 box - - ingest/muxer.go:1158 [gw@1 tagvalue="4" ingester="S3 Ingester" ingesteruuid="b4a30638-3ce3-4bd6-be4d-802e7cc55537"] Got entry tagged with completely unknown intermediate tag, dropping it`

### What were you expecting to happen?

not that error

### Any logs, error output, etc?

see above

### Any other comments?

i manually verified that the resolved tag value was 1, NOT 4.  So process batch did something dumb

### What versions of software are you using?

5.1.2 prod

**Comment by ashnwade** [comment]
Wasn't real.  Test confirmed.
