### ISSUE TITLE
S3 Ingester SQS dance

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#550]
## Who was the customer who requested this feature?

Several

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

This reduces some strain on the ingester by removing the need to do a full object walk during scan, we can object walk at startup then attach to the SQS queue and watch for changes.

Overwall this will allow for a much better experience when a bucket might have a ton of objects or require more responsive ingest.

## How does this feature address the above problem?

Eliminates the need for a complete S3 walk at regular intervals.

## Any other comments?

Medium priority

**Comment by kris-watts-gravwell** [comment]
direct customer request, moving up priority

**Comment by david-fritz-gravwell** [comment]
Declared working!
