### ISSUE TITLE
SNMP trap ingester: people want it

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#564]
## What is the feature to be added?

An ingester that can receive SNMP traps and ingest them

Some qualifications on this ingester to keep it simple:
1. Listen only, no polling
2. Ingest traps as they are, no polling to resolve MIBs

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

Many switches and routers can't log critical events via standard logging channels, SNMP Traps allow for at least capturing those events.

## How does this feature address the above problem?

Gets logs where there may not be any

## Any other comments?

Cisco is going to do dumb stuff, so make sure to test on them.

**Comment by john-floren-gravwell** [comment]
@kris-watts-gravwell do we know either of the following:

1. What version of SNMP they want to use?
2. What devices they intend to use?

**Comment by kris-watts-gravwell** [comment]
1. no
2. no
