### ISSUE TITLE
go.mod replace directives are breaking out of tree builds

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#575]
### What are the steps to reproduce this issue?

1. Create a super simple ingester outside the main tree (example attached)

2. build it

### What happens?

it can't build

### What were you expecting to happen?

that it would build

### Any logs, error output, etc?

```
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1264:34: undefined: jsonparser.FuzzDelete
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1265:35: undefined: jsonparser.FuzzEachKey
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1266:38: undefined: jsonparser.FuzzGetBoolean
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1267:36: undefined: jsonparser.FuzzGetFloat
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1268:34: undefined: jsonparser.FuzzGetInt
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1269:37: undefined: jsonparser.FuzzGetString
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1270:43: undefined: jsonparser.FuzzGetUnsafeString
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1271:38: undefined: jsonparser.FuzzObjectEach
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1272:37: undefined: jsonparser.FuzzParseBool
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1273:38: undefined: jsonparser.FuzzParseFloat
/home/kris/mygo/pkg/mod/github.com/gravwell/gravwell/v3@v3.8.15/ingest/processors/plugin/packages.go:1273:38: too many errors
```

### Any other comments?

I think THIS is the problem:
```
replace github.com/buger/jsonparser => github.com/floren/jsonparser v0.0.0-20210727191945-e5063027fceb
```

### What versions of software are you using?
5.1.3

# Replace directives we have:

- [ ]  buger/jsonparser: PR is in, https://github.com/buger/jsonparser/pull/180
- [X] open-networks/go-msgraph: my PR has been merged, so we should be able to get rid of it
- [x] fsnotify/fsnotify: @kris-watts-gravwell needs to do a PR, we'll see if we can get it upstreamed.

**Comment by john-floren-gravwell** [comment]
I think we can get rid of the msgraph replace, because they merged my PR: https://github.com/open-networks/go-msgraph/pull/3

I will test this.

**Comment by john-floren-gravwell** [comment]
I updated my PR for the jsonparser library, which is very minimal.

**Comment by john-floren-gravwell** [comment]
@kris-watts-gravwell it looks like your fsnotify fork is very close to the upstream; have you considered doing a PR? Or have they indicated they're not interested?

**Comment by john-floren-gravwell** [comment]
https://github.com/buger/jsonparser/pull/180 I feel like this is a pretty straightforward fix but it's been pocketed for years now.

**Comment by kris-watts-gravwell** [comment]
i will push a PR up to fsnotify, some of the others will likely need full up forks on some of these.

Lets just get this moving and punt as needed.

**Comment by kris-watts-gravwell** [comment]
i suggest that this be a longer term project, lets keep walking this issue forward so we don't lose it, but we can just track which replace directives have upstream PRs, which are accepted, etc...

**Comment by kris-watts-gravwell** [comment]
PR for fsnotify is in: https://github.com/fsnotify/fsnotify/pull/550

**Comment by kris-watts-gravwell** [comment]
I am making the call, we fork jsonparser and use our fork.  Check the other PRs that are also idling, there might be some more goodness/stability fixes in them too.

I am working with a dev on fsnotify to get our shit fixed there, then we can update the fsnotify lib

**Comment by john-floren-gravwell** [comment]
We got rid of the replace, finally.
