### ISSUE TITLE
WinEvent truncating entries

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#582]
### What are the steps to reproduce this issue?

Unknown at this time

### What happens?

Customer report that some Windows Event logs are truncated.  Namely EventID 5140 and 5145.

What windows shows:
![OG](https://user-images.githubusercontent.com/108431167/208336834-7b348c56-345b-45c1-ac05-a3ade29c110c.png)

What is seen in Gravwell:
![truncated](https://user-images.githubusercontent.com/108431167/208336848-9ca08028-d0c4-468a-940a-c6e746fe4ceb.png)

### What were you expecting to happen?

not truncate log events

### Any logs, error output, etc?

See above screenshots

### Any other comments?

The events are related to network share accesses, maybe investigate if the messages are extremely long due to very long file names?

To tweak windows to log the 5140 and 5145 messages:
![enable logging](https://user-images.githubusercontent.com/108431167/208337021-243225e2-5215-47c1-8e0c-63f5051c99f6.png)
![logsetup](https://user-images.githubusercontent.com/108431167/208337036-18e51bcb-6aa0-48ec-b16c-988ebbeb0bc3.png)

### What versions of software are you using?

Winevent ingester version 5.1.1
Windows Server 2019

**Comment by kris-watts-gravwell** [comment]
may not actually be truncating?

![Image](https://user-images.githubusercontent.com/108431167/208790189-3aebaa3b-7f9c-4f25-af0b-a2218b7199e0.png)

**Comment by kris-watts-gravwell** [comment]
likely not an ingester issue but a windows WEF issue.   User confirmed that the logs are coming in via WEF.

Here is a discussion about it: https://community.splunk.com/t5/Getting-Data-In/Why-is-Windows-event-log-message-data-being-truncated-and-only/m-p/231310

with potential solution by the user.

**Comment by kris-watts-gravwell** [comment]
customer indicated that their stuff is already in the right transport format as indicated by that link.

**Comment by kris-watts-gravwell** [comment]
I think a NULL is making its way into the AccessList data object and the UTF16->UTF8 converter is hand rolled.

Of course the windows docs say its not possible to have a NULL in there, but it certainly looks like there is one.

We are going to move over to a different text handling package to turn the UTF16 XML into UTF8 string that we ship that won't stop on NULLs, but rather do proper rune conversions.

**Comment by kris-watts-gravwell** [comment]
moving to 5.2.1 to make sure we check in with customer to see if issue is resolved with changes

**Comment by ashnwade** [comment]
check in with customer again before 5.2.2 release
