### ISSUE TITLE
Tag specification: CheckTag doesn't ACTUALLY control all the characters that should be rejected

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#674]
https://pkg.go.dev/github.com/gravwell/gravwell/v3/ingest#CheckTag

That isn't strict enough.

Having another `RemapTagname(tagname string, mp rune) (string, error)` that changes all the bad chars over to the mp remap rune would be super handy too

**Comment by david-fritz-gravwell** [comment]
Internally (and partially documented at https://docs.gravwell.io/search/spec.html), a constraint r-value is defined as:

1. All printable characters, except whitespace and the following runes: |, {, }, (, ), ;, =, <, !, >, ~, %, ^, &, +, ", ., :, ,', /
2. A quoted string, which includes all unicode code-points (including the characters disallowed in 1., up to the end double quote. Escaping double quotes is allowed.

Additionally, escape characters are always interpreted and unescaped, INCLUDING hex and unicode escapes (\x \u etc). 

@kris-watts-gravwell This is easy to bring into the ingest library.

**Comment by kris-watts-gravwell** [comment]
do you know what the set of utf-8 character masks are that we should allow?

https://pkg.go.dev/unicode#RangeTable

@david-fritz-gravwell

**Comment by david-fritz-gravwell** [comment]
Things that should be disallowed:

- whitespace IsSpace()
- control characters IsControl()
- Single, double, and backtick quotes
- Backslash
- Our own tag expansion stuff: [ ] *
- Special gravwell syntax: @ $
- Our ops: ! < > = ~

**Comment by kris-watts-gravwell** [comment]
Vote on hard NO
* space
* backslash
* any type of quotes ' " ` and bullshit R/L hand quotes
* no brackets of any kind []{}<>()
* no pipe (|)

**Comment by kris-watts-gravwell** [comment]
also no globbing pattern characters:
* \* ^ ! $
