### ISSUE TITLE
Client needs `HasCapability()` function 

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#720]
## What is the enhancement to be made?

Client needs a "HasCapability" function that can populate current user capabilities (if they are not populated) and then check if the user has the given capability.

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

Tons of functions need to check if a capability exists prior to firing

## Any other comments?

do it.

**Comment by john-floren-gravwell** [comment]
we're using it, it's fine
