### ISSUE TITLE
jsontimeextract: not handling unix, unix milli, or unix nano timestamps

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#769]
## What are the steps to reproduce this issue?

1. Configure simple relay with the following config:
```
[Listener "testing"]
	Bind-String="0.0.0.0:8888"
	Tag-Name=testdata
	Preprocessor="json-split"
	Preprocessor="json-timestamp"

[preprocessor "json-split"]
	Type=jsonarraysplit
	Extraction=messages
	Force-JSON-Object=false

[Preprocessor "json-timestamp"]
	Type=jsontimeextract
	Path="date"
	Timestamp-Override="UnixSeconds"
```
2. Throw an entry that looks like so:
```
{"id": 123123123, "messages": [{"id": 1214234, "type": "message", "date": 1655123412}, {"id": 1214235, "type": "message", "date": 1655123413}]}
```

## What happens?

The timestamps `1655123413` and `1655123414` are NOT handled.

But if we use a different timestamp preprocessor:
```
[Preprocessor "ts"]
	Type=regextimestamp
	Regex=`"date":\s?(?P<ts>\d+)`
	TS-Match-Name=ts
	Timestamp-Format-Override="UnixSeconds"
```

it DOES work

## What were you expecting to happen?

jsontimeextract to handle the timestamp

## Any other comments?

Seems like jsontimeextract isn't handling timestamps the same way as regexextract

## What versions of software are you using?

5.3.2

**Comment by kris-watts-gravwell** [comment]
i wonder if that preprocessor isn't using timegrinder but `time.Parse` directly?

**Comment by kris-watts-gravwell** [comment]
we saw this issue with a customer, bumping priority and moving forward into current milestone

**Comment by david-fritz-gravwell** [comment]
Is this because the `[{"id": 1214234,` portion, which occurs first, is being ingested as `Thu Jan 15 1970 01:17:14 GMT+0000`?

**Comment by david-fritz-gravwell** [comment]
In the example above, the path is set to `date`, but the path in the example json is something like `messages[0].date`. Could that be the culprit?

**Comment by kris-watts-gravwell** [comment]
turns out it was the json walking code, fixed here: https://github.com/gravwell/gravwell/pull/794
