### ISSUE TITLE
FileFollower: at startup scan the state file and clean

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#779]
## What is the enhancement to be made?

At startup the FileFollower should load the state file and walk the entries in it comparing against the configured follower blocks.  If there is an entry that is NOT applicable to all configured ingesters we should remove it from the state and flush it.

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

The ingester tends to bark about trying to attach to files that do not exist if the file exists in the state file.

## Any other comments?

Nice to have, not critical

**Comment by kris-watts-gravwell** [comment]
this appears to already be happening?  I am not sure how it was logging about trying to follow a file that does not exist when the listener block doesn't exist.

**Comment by john-floren-gravwell** [comment]
Note that the issue in question happened on Scientific Linux 6 (3 years past EOL, trying to figure out the kernel version) when pointed at the bro "current" directory, which gets rotated in a truly nasty way which has continually caused us issues forever

**Comment by kris-watts-gravwell** [comment]
this is a non-issue, this exact functionality is in there.
