### ISSUE TITLE
ingest: change all ingesters to use ProcessContext() instead of Process()

### ISSUE THREAD

**Issue by david-fritz-gravwell** [gravwell/gravwell#836]
## What are the steps to reproduce this issue?

1. Ingest and get into a very bad state -- disk full + cache full
2. Try to exit

## What happens?

If you aren't using ProcessContext(), we can't gracefully shutdown.

**Comment by kris-watts-gravwell** [comment]
this is as good as its going to get, if we are waiting to push something to disk and kernel says no, or blocks, there is no good way to get out.
