### ISSUE TITLE
Additional offset based timezone specifications

### ISSUE THREAD

**Issue by traetox** [gravwell/gravwell#90]
```
/ # TZ=Asia/Tokyo date
Sat Oct  3 15:45:34 UTC 2020
/ # TZ=JST-9 date
Sun Oct  4 00:45:38 JST 2020
```

**Comment by floren** [comment]
A few notes from investigation:

* Formats like "JST-9" are a POSIX timezone specification, which is now generally considered insufficient for real-world timekeeping applications and is deprecated in favor of proper IANA timezones (e.g. "Asia/Tokyo")

* `TZ=Asia/Tokyo date` works fine on my system, but may not work on systems where the timezone database (often /usr/share/zoneinfo or /usr/share/lib/zoneinfo) is not installed. On Debian systems, this is installed by a package named tzdata.

* Go has no code implemented to parse POSIX-formatted timezones; we would have to implement it outselves.

**Comment by floren** [comment]
Initial bug report was using busybox "date" command, which doesn't seem to respect the TZ variable. IANA formatting deemed acceptable.
