### ISSUE TITLE
the stderr error logger should not contain entire RFC5424 message

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#901]
## What are the steps to reproduce this issue

1. Install an ingester
2. Route systems syslog out to our ingester
3. observe output

## What happens?

This is what the entry is:
```
<30>1 2023-11-16T23:27:22.725587+00:00 hostname gravwell_simple_relay 35859 - -  <14>1 2023-11-16T23:27:22.721015Z hostname simplerelay - SimpleRelay/main.go:219 [gw@1 ingesteruuid="a9ae46fc-0312-47aa-b5ed-1be8b1330000" active="9"] Closing active connections
```

## What were you expecting to happen?

Just emit the ` [gw@1 ingesteruuid="a9ae46fc-0312-47aa-b5ed-1be8b1330000" active="9"] Closing active connections` portion when sending to stderr

## Any other comments?

the syslog  relay/journal/whatever already puts an appname and header on it, we shouldn't do that too

This also happens in the windows internal logging, we emit a full RFC5424 message into the windows event logger, thats bad.

## What versions of software are you using?

5.4.2

**Comment by david-fritz-gravwell** [comment]
I'm still seeing full RFC5424 messages on fatal logs to stderr:

```
√ valinor:gravwell/ingesters/HttpIngester % ./HttpIngester -config-file test.conf


^C<11>1 2023-11-29T14:41:45.315424-07:00 valinor httpingester - HttpIngester/main.go:177 [gw@1 error="http: Server closed"] failed to serve HTTP server
```

**Comment by kris-watts-gravwell** [comment]
You will because you did not redirect stderr so we assume you are in debug mode


without redirecting stderr, everything goes to stderr


WITH redirecting stderr, only fatal goes to stderr

**Comment by david-fritz-gravwell** [comment]
When I run as above, _only_ fatal messages come to stderr, and the rest go to the log location. But yes, when I redirect stderr, it trims the output to just the message and structured output.

LGTM
