### ISSUE TITLE
Stderr should not receive all internal log message, only fatal

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#902]
## What are the steps to reproduce this issue?

1. Start any gravwell ingester/component
2. look at journal

## What happens?

all of our debug logs and info logs are in there

## What were you expecting to happen?

we should ONLY wire fatal logs out to stderr

## Any other comments?

error is debatable, but definitely not info, and warn

## What versions of software are you using?

5.4.2

**Comment by david-fritz-gravwell** [comment]
LGTM
