### ISSUE TITLE
s3 ingester: add filter glob or regex to sqs/s3 listener

### ISSUE THREAD

**Issue by david-fritz-gravwell** [gravwell/gravwell#958]
## What is the enhancement to be made?

The bucket listener in the s3 ingester has a File-Filters field. We need something equivalent in the sqs/s3 listener.

**Comment by ashnwade** [comment]
![Image](https://github.com/gravwell/gravwell/assets/107071905/2b250d06-ce77-4704-a484-953aacf6c5da)
